MMELGAR<-read.csv("~/PETM-shiny/MODEL_RESULTS/MODEL_RESULTS_2017-04-26.csv",sep = "")
library(data.table)
MMELGAR<-as.data.table(MMELGAR)
MMELGAR<-MMELGAR[L=="38" & P_TRIAT>=1]
x11()
plot(MMELGAR$LATITUDE,MMELGAR$LONGITUDE) 
plot(MMELGAR$LATITUDE,MMELGAR$LONGITUDE)

BASE_ROCIADO <-read.csv('~/PETM-shiny/ATTACK_DATA_2006_2015/ATTACK_2006_2015.csv')
BASE_ROCIADO<-as.data.table(BASE_ROCIADO)
BASE_ROCIADO <- BASE_ROCIADO[which(!duplicated(BASE_ROCIADO$UNICODE)),]
puntos<-read.csv('~/CLAUDIA-DATOS-/AQP_GPS_GOOGLE_18_02_2017/AQP_GPS_GOOGLE_corregido.csv')
DATA<-merge(BASE_ROCIADO,puntos,by='UNICODE',all.x = TRUE)
ADICIONALES<-DATA[which(is.na(DATA$LATITUDE))]
ADICIONALES<-as.data.table(ADICIONALES)
ADICIONALES<-ADICIONALES[,c('UNICODE','LATITUDE','LONGITUDE')]
write.csv(ADICIONALES,'~/CLAUDIA-DATOS-/ADICIONALES.csv',row.names = FALSE)
